#!/usr/bin/env bash

bat=`cat /sys/class/power_supply/BAT0/capacity`

if [ `cat /sys/class/power_supply/BAT0/status` = "Discharging" ]; then
	plug=0
else
	plug=1
fi

echo "B$plug$bat" > /tmp/statuspipe.fifo

if [ $plug == 0 ] && [ "$bat" -le "100" ]; then
	notify-send --urgency=critical "Low Battery" $bat
fi

if [ $plug == 0 ] && [ "$bat" -le "3" ]; then
	systemctl hibernate
fi

exit 0
