#!/bin/bash
bg="#002b36"
fg="#93a1a1"
ffg="#859900"

line=`xrandr | head -1`
set -- $line
shift 7
width=$1

rofi -show run \
 -width $width \
 -columns 1 \
 -color-window "${bg},${bg}" \
 -color-normal "${bg},${fg},${bg},${bg},${ffg}" \
 -bc "$bg" \
 -location 0 \
 -lines 8 \
 -bw 0 \
 -font "Fira Mono Medium 16" \
 -padding 400 \
 -separator-style none \
 -opacity 90 -hide-scrollbar
