#!/bin/bash
bg="#282828"
fg="ebdbb2"
ffg="#fb4934"

line=`xrandr | head -1`
set -- $line
shift 7
width=$1
height=${3::-1}
padding=$(($height / 3))

rofi -show run \
 -width $width \
 -columns 1 \
 -color-window "${bg},${bg}" \
 -color-normal "${bg},${fg},${bg},${bg},${ffg}" \
 -bc "$bg" \
 -location 0 \
 -lines 8 \
 -bw 0 \
 -font "Fira Mono Medium 16" \
 -padding $padding \
 -separator-style none \
 -opacity 90 -hide-scrollbar
