#!/bin/sh

read input

length=${#input}
length=$((length + 10))
#length=$((length * 2.5))
length=$(echo "$length*3.2" | bc)


line=`xrandr | head -1`
set -- $line
shift 9
height=${1::-1}
y=$((height-19))

date=$(date "+%H.%M")
vol=`amixer get Master | grep -oE "[[:digit:]]*%" | sed 's/.$//'`

echo "  ${date}  /  ${input}" | dzen2 -e 'onstart=uncollapse' -ta l -p 1 -y $y -x 0 -w $length -fn 'Fira Mono:Medium:size=9' -bg "#268bd2" -fg "#002B36"
